services:
  - type: web
    name: automatehub-backend
    runtime: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm install && ls -la src/models/
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false 